server:
  port: 8084

user-service:
  auth-server:
    host: localhost
    port: 8080
  database:
    mongo:
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  bucket-name: booking-bucket-1

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: ${user-service.database.mongo.host}
      port: ${user-service.database.mongo.port}
      database: users
  rabbitmq:
    host: ${user-service.rabbitmq.host}
    port: ${user-service.rabbitmq.port}
    username: ${user-service.rabbitmq.username}
    password: ${user-service.rabbitmq.password}
  cloud:
    gcp:
      credentials:
        location: classpath:gcp-account-file.json
    config:
      enabled: false
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        input:
          destination: users
          group: usersGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit.bindings.input.consumer:
        autoBindDlq: true
        republishToDlq: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${user-service.auth-server.host}:${user-service.auth-server.port}/realms/booking/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/realms/booking
---
spring:
  config:
    activate:
      on-profile: docker

user-service:
  auth-server:
    host: keycloak
  database:
    mongo:
      host: mongo
  rabbitmq:
    host: rabbitmq
    username: default_user_XhVRPRZIV6v4Kkn3VOU
    password: kePZ_VoNHTqJU4pxuIY8RlaWPhA9Bwv6

---
spring:
  config:
    activate:
      on-profile: kubernetes

user-service:
  auth-server:
    host: keycloak
  database:
    mongo:
      host: mongo
  rabbitmq:
    host: rabbitmq
    username: default_user_DUkcxxwyn9gFzfgFrvi
    password: W5xjFWTF6CE_XGeBf9jGRFwyqvB7xJ23

