server:
  port: 8765

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
#              - GET
#              - POST
#              - PUT
#              - DELETE
            allowedHeaders: "*"
              # - Authorization
      routes:
        - id: booking
          uri: lb://booking-service
          predicates:
            - Path=/booking/**

  security.oauth2.resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/auth/realms/booking/protocol/openid-connect/certs
          issuer-uri: http://localhost:8080/auth/realms/booking

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://zipkin-server:9411
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server:8761/eureka/