eureka:
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 5
    prefer-ip-address: true
  client:
    healthcheck.enabled: true
    serviceUrl:
      defaultZone: http://${app.discovery-server.host}:${app.discovery-server.port}/eureka
    initial-instance-info-replication-interval-seconds: 5
    registry-fetch-interval-seconds: 5

app:
  discovery-server:
    host: localhost
    port: 8761
  database:
    mongo:
      host: localhost
      port: 27017
  messaging:
    rabbitmq.host: 127.0.0.1

spring:
  rabbitmq:
    host: ${app.messaging.rabbitmq.host}
    port: 5672
    username: guest
    password: guest

---
spring:
  config:
    activate:
      on-profile: docker

app:
  database:
    mongo:
      host: mongodb
  discovery-server:
    host: discovery-server
  messaging:
    rabbitmq.host: rabbitmq
