server:
  port: 8083

spring:
  cloud:
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        output-properties:
          destination: properties
          producer.required-groups: auditGroup
        output-users:
          destination: users
          producer.required-groups: auditGroup
  security.oauth2.resourceserver:
    jwt:
      jwk-set-uri: http://localhost:8090/auth/realms/booking/protocol/openid-connect/certs
      issuer-uri: http://localhost:8090/auth/realms/booking

app:
  property-service:
    host: property-service
  user-service:
    host: user-service

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://zipkin-server:9411
server:
  port: 8082