server:
  port: 8081

spring:
  cloud:
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings.input:
        destination: properties
        group: propertiesGroup
        consumer:
          maxAttempts: 3
          backOffInitialInterval: 500
          backOffMaxInterval: 1000
          backOffMultiplier: 2.0
      rabbit.bindings.input.consumer:
        autoBindDlq: true
        republishToDlq: true
  datasource:
    platform: mysql
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
    url: jdbc:mysql://localhost:3307/property_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
    initialization-mode: ALWAYS

---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://zipkin-server:9411
  datasource:
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
    url: jdbc:mysql://mysql:3308/property_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    initialization-mode: ALWAYS
server:
  port: 8081
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://discovery-server:8761/eureka/