server:
  port: 8082

spring:
  data:
    mongodb:
      host: ${app.database.mongo.host}
      port: ${app.database.mongo.port}
      database: users

#  data:
#    mongodb:
#      uri: mongodb+srv://nick-pat:1996nikolas@bkcluster.jaoqj.mongodb.net/userDB?retryWrites=true&w=majority
#      database: userDB
      #port: 27017
  cloud:
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings.input:
        destination: users
        group: usersGroup
        consumer:
          maxAttempts: 3
          backOffInitialInterval: 500
          backOffMaxInterval: 1000
          backOffMultiplier: 2.0
      rabbit.bindings.input.consumer:
        autoBindDlq: true
        republishToDlq: true


---
spring:
  config:
    activate:
      on-profile: docker
  zipkin:
    baseUrl: http://zipkin-server:9411
server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-server:8761/eureka/