version: '3.9'

services:
  config-server:
    build: booking-cloud-infra/config-server
    container_name: config-server
    mem_limit: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8888:8888

  discovery-server:
    build: booking-cloud-infra/discovery-server
    container_name: discovery-server
    mem_limit: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8761:8761
    depends_on:
      - config-server

  api-gateway:
    build: booking-cloud-infra/api-gateway
    container_name: api-gateway
    mem_limit: 512M
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8765:8765
    depends_on:
      - config-server
      - discovery-server

  property-service:
    links:
      - mysql
    build: booking-services/property-service
    mem_limit: 700m
    container_name: property-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8081:8081
    depends_on:
      - config-server
      - rabbitmq
      - mysql

  user-service:
    build: booking-services/user-service
    mem_limit: 700m
    container_name: user-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8082:8082
    depends_on:
      - config-server
      - rabbitmq
      - mongodb

  booking-service:
    build: booking-services/booking-service
    mem_limit: 700m
    container_name: booking-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - 8083:8083
    depends_on:
      - config-server
      - rabbitmq

  mongodb:
    container_name: booking-mongo
    image: mongo:4.2.6-bionic
    ports:
      - "27017-27019:27017-27019"

  mysql:
    image: mysql
    # restart: always
    container_name: booking-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: property_db
    ports:
      - "3308:3308"
    volumes:
      - "./db:/var/lib/mysql"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: booking-rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  zipkin-server:
    image: openzipkin/zipkin
    container_name: booking-zipkin
    mem_limit: 512M
    ports:
      - 9411:9411
    depends_on:
      - rabbitmq
