version: '2'

services:
  property-service:
    links:
      - mysql
    image: nicholaspat/property-service
    mem_limit: 700m
    container_name: property-service
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mysql
    ports:
      - 8081:8081

  reservation-service:
    links:
      - mongo
    image: nicholaspat/reservation-service
    mem_limit: 700m
    container_name: reservation-service
    environment:
#      - MONGODB_HOST=mongo
#      - MONGODB_PORT=27017
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - mongo
    ports:
      - 8083:8083

  mysql:
    image: mysql
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=property_db
    ports:
      - 3306:3306
    volumes:
      - "./mysql-volume:/var/lib/mysql"

  mongo:
    container_name: mongodb
    image: mongo:4.2.6-bionic
    ports:
      - "27017-27019:27017-27019"
