version: '3.9'

services:
  config-server:
    image: nicholaspat/booking-config-server
    container_name: config-server
    mem_limit: 512M
    ports:
      - 8888:8888

  mysql:
    image: mysql
    restart: always
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: booking
    ports:
      - "3306:3306"
    volumes:
      - "./db:/var/lib/mysql"

#  zipkin-server:
#    image: openzipkin/zipkin
#    container_name: zipkin-server
#    mem_limit: 512M
#    ports:
#      - 9411:9411

  discovery-server:
    image: nicholaspat/booking-discovery-server
    container_name: discovery-server
    mem_limit: 512M
    ports:
      - 8761:8761
    depends_on:
      - config-server
    entrypoint: ["./dockerize","-wait=tcp://config-server:8888","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]

  api-gateway:
    image: nicholaspat/api-gateway
    container_name: api-gateway
    mem_limit: 512M
    ports:
      - 8765:8765
    depends_on:
      - config-server
      - discovery-server
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]

  property-service:
    links:
      - mysql
    image: nicholaspat/booking-property-service
    mem_limit: 700m
    container_name: property-service
    ports:
      - 8081:8081
    depends_on:
      - config-server
      - discovery-server
      - mysql
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]

  user-service:
    links:
      - mysql
    image: nicholaspat/user-service
    mem_limit: 700m
    container_name: user-service
    ports:
      - 8082:8082
    depends_on:
      - config-server
      - discovery-server
      - mysql
    entrypoint: ["./dockerize","-wait=tcp://discovery-server:8761","-timeout=60s","--","java", "org.springframework.boot.loader.JarLauncher"]
