#app:
#  config-server:
#    host: localhost
#    port: 8888

#spring:
#  application.name: discovery-server
#  cloud.config:
#    fail-fast: true
#    retry:
#      initial-interval: 3000
#      multiplier: 1.3
#      max-interval: 10000
#      max-attempts: 20
#    uri: http://${app.config-server.host}:${app.config-server.port}

#
spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: discovery-server

---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888

#app:
#  config-server:
#    host: config-server
#    import: optional:configserver:http://config-server:8888