app:
  config-server:
    host: localhost
    port: 8888

spring:
  config:
    import: optional:configserver:http://${app.config-server.host}:${app.config-server.port}
  application:
    name: discovery-server

---
spring:
  config:
    activate:
      on-profile: docker
app:
  config-server:
    host: config-server
    #import: optional:configserver:http://config-server:8888