apiVersion: v1
kind: Service
metadata:
  labels:
    app: property-service
  name: property-service
spec:
  type: ClusterIP
  ports:
    - name: "8081"
      port: 8081
      targetPort: 8081
  selector:
    app: property-service
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: property-service
data:
  SPRING_PROFILES_ACTIVE: kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: property-service
  name: property-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: property-service
  template:
    metadata:
      labels:
        app: property-service
    spec:
      containers:
        - image: nicholaspat/property-service
          name: property-service
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: property-service
            - name: DATABASE_HOST
              value: mysql
            - name: DATABASE_PORT
              value: "3306"
      restartPolicy: Always
