server.port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nickPaterakis/booking-config.git
          username: nickPaterakis
          password: 1996NikO!@$
        native:
          searchLocations: file:///config/repo

---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config.server.native.searchLocations: file:/config/repo