server.port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/nickPaterakis/booking-config.git
          username: nickPaterakis
          password: 1996NikO!@$
        native:
          searchLocations: file:///${GIT_REPO}
  #          uri: file:///C:/Users/Nicholas/Documents/Projects/Spring/booking/git-local-config-repo
  application:
    name: booking-config-server
---
spring:
  config:
    activate:
      on-profile: docker
  cloud:
    config.server.native.searchLocations: file:/config/repo