server:
  port: 8084

app:
  auth-server:
    host: localhost
    port: 8090
  database:
    mongo:
      host: localhost
      port: 27017
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

spring:
  application:
    name: user-service
  data:
    mongodb:
      host: ${app.database.mongo.host}
      port: ${app.database.mongo.port}
      database: users
  rabbitmq:
    host: ${app.rabbitmq.host}
    port: ${app.rabbitmq.port}
    username: ${app.rabbitmq.username}
    password: ${app.rabbitmq.password}
  cloud:
    gcp:
      credentials:
        location: classpath:key.json
    config:
      enabled: false
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        input:
          destination: users
          group: usersGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
      rabbit.bindings.input.consumer:
        autoBindDlq: true
        republishToDlq: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/auth/realms/booking/protocol/openid-connect/certs
          issuer-uri: http://localhost:8090/auth/realms/booking

#          jwk-set-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/booking/protocol/openid-connect/certs
#          issuer-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/booking
---
spring:
  config:
    activate:
      on-profile: kubernetes
  zipkin:
    baseUrl: http://zipkin-server:9411

app:
  auth-server:
    host: 34.123.156.85
  database:
    mongo:
      host: mongo
  rabbitmq:
    host: rabbitmq
    username: c9X2ij1fJJ04Om4nab3tHU56pTbH660B
    password: OXlN-b_3Sdyag6-W_d6ftji9-izGBnsl
