spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: api-gateway

---
spring:
  config:
    activate:
      on-profile: docker
    import: optional:configserver:http://config-server:8888

