#spring:
#  config:
#    import: optional:configserver:http://localhost:8888
#  application:
#    name: property-service
#
#---
#spring:
#  config:
#    activate:
#      on-profile: docker
#    import: optional:configserver:http://config-server:8888

server:
  port: 8081

app:
  user-service:
    host: localhost
    port: 8082
  reservation-service:
    host: localhost
    port: 8083
  auth-server:
    host: 34.123.156.85
    port: 8080
  database:
    mysql:
      host: localhost
      port: 3306


spring:
  application:
    name: property-service
  cloud:
    config:
      enabled: false
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        input:
          destination: properties
          group: propertiesGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
        output-users:
          destination: users
          producer.required-groups: auditGroup
        output-reservations:
          destination: reservations
          producer.required-groups: auditGroup
      rabbit.bindings.input.consumer:
        autoBindDlq: true
        republishToDlq: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
    url: jdbc:mysql://${app.database.mysql.host}:${app.database.mysql.port}/property_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
    initialization-mode: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8090/auth/realms/booking/protocol/openid-connect/certs
          issuer-uri: http://localhost:8090/auth/realms/booking
#          jwk-set-uri: http://34.123.156.85:8080/auth/realms/booking/protocol/openid-connect/certs
#          issuer-uri: http://34.123.156.85:8080/auth/realms/booking

#      jwk-set-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/booking/protocol/openid-connect/certs
#      issuer-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/booking

---
spring:
  config:
    activate:
      on-profile: kubernetes
  zipkin:
    baseUrl: http://zipkin-server:9411

app:
  user-service:
    host: user-service
  reservation-service:
    host: reservation-service
  auth-server:
    host: 34.123.156.85
  database:
    mysql:
      host: mysql