server:
  port: 8081

app:
  user-service:
    host: localhost
    port: 8084
  reservation-service:
    host: localhost
    port: 8083
  auth-server:
    host: 34.123.156.85
    port: 8080
  database:
    mysql:
      host: localhost
      port: 3306
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

bucketname: bookinguniwa
subdirectory: images

spring:
  application:
    name: property-service
  rabbitmq:
    host: ${app.rabbitmq.host}
    port: ${app.rabbitmq.port}
    username: ${app.rabbitmq.username}
    password: ${app.rabbitmq.password}
  cloud:
    config:
      enabled: false
    gcp:
      credentials:
        location: classpath:key.json
    stream:
      defaultBinder: rabbit
      default.contentType: application/json
      bindings:
        input:
          destination: properties
          group: propertiesGroup
          consumer:
            maxAttempts: 3
            backOffInitialInterval: 500
            backOffMaxInterval: 1000
            backOffMultiplier: 2.0
        output-users:
          destination: users
          producer.required-groups: auditGroup
        output-reservations:
          destination: reservations
          producer.required-groups: auditGroup
      rabbit.bindings.input.consumer:
        autoBindDlq: true
        republishToDlq: true
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    schema: classpath*:db/schema.sql
    data: classpath*:db/data.sql
    url: jdbc:mysql://${app.database.mysql.host}:${app.database.mysql.port}/property_db?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root
    hikari:
      initialization-fail-timeout: 60000
      connection-test-query: SELECT 1
      maximum-pool-size: 10
    initialization-mode: ALWAYS
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://34.123.156.85:8080/auth/realms/booking/protocol/openid-connect/certs
          issuer-uri: http://34.123.156.85:8080/auth/realms/booking
      client:
        registration:
          keycloak:
            client-id: 'booking-spring-boot-app-client'
            client-secret: '64fbd0f5-4faf-49ac-99a7-518c72b7b327'
#            authorizationGrantType: client_credentials
            clientName: Keycloak
            authorizationGrantType: authorization_code
            redirectUri: '{baseUrl}/login/oauth2/code/{registrationId}'
            scope:
              - openid
              - profile
              - email
        provider:
          keycloak:
            issuerUri: http://34.123.156.85:8080/auth/realms/booking
            user-name-attribute: name

#      jwk-set-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/booking/protocol/openid-connect/certs
#      issuer-uri: http://${app.auth-server.host}:${app.auth-server.port}/auth/realms/booking

---
spring:
  config:
    activate:
      on-profile: kubernetes
  zipkin:
    baseUrl: http://zipkin-server:9411

app:
  user-service:
    host: user-service
  reservation-service:
    host: reservation-service
  auth-server:
    host: 34.123.156.85
  database:
    mysql:
      host: mysql
  rabbitmq:
    host: rabbitmq
    username: c9X2ij1fJJ04Om4nab3tHU56pTbH660B
    password: OXlN-b_3Sdyag6-W_d6ftji9-izGBnsl